### ISSUE TITLE
Card match function, flip non matching pairs

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#11]
Build a function to check if the cards match by pairs. If they match make them disappear from the screen. If they do not match make them flip back over.

**Comment by morgsmccauley** [comment]
I'll grab this one! 👍

**Comment by Jayadev6191** [comment]
@morgsmccauley Sorry, I did not see your comment when I saw this issue.

**Comment by morgsmccauley** [comment]
No problem! Did the work anyway so raised another PR (#13) :)

**Comment by 3daddict** [comment]
Great work @morgsmccauley  and @Jayadev6191
