### ISSUE TITLE
Create button to populate cards on DOM in random order

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#15]
Create a Start Game button that when pressed will populate the cards on the dom in a random order each time.

**Comment by fllprbt** [comment]
Can I have it?

**Comment by 3daddict** [comment]
@fllprbt sure!

**Comment by DevDigression** [comment]
Apologies..new to open source contributions. I should have looked here first. I just submitted a PR for this issue; feel free to cancel!

**Comment by 3daddict** [comment]
@DevDigression no problem, looking at the code nice work! Great job on the code clean up. I'll merge to a test branch and if alls good we'll update master.

**Comment by 3daddict** [comment]
> Apologies..new to open source contributions. I should have looked here first. I just submitted a PR for this issue; feel free to cancel!

@DevDigression I tested out the pull request and I am getting a weird effect. When a card is clicked it randomly changes. When the page loads the dom should be blank, then when the button is pressed the cards should populate the dom in a random order.

**Comment by fllprbt** [comment]
@DevDigression second time today that this happens in the middle of development. As far as it is unintentional and you are new I have no issue ofc. 

@3daddict it will help people (especially newcomers) if you create an assigned label to attach after each issue is being assigned to someone + mention to issue description that they have to ask for it first.

Here is another example from a project I am contributing that sums up what I have described:
https://github.com/lingui/js-lingui/issues/349

Happy coding.

**Comment by 3daddict** [comment]
@fllprbt I am also learning thank you for the great advice and please feel free to proceed with your code for this feature.

**Comment by DevDigression** [comment]
@3daddict Whoops..sorry about that too! I noticed I was missing the function invocation - it wasn't being called as an instance on click. Submitting new PR now!
