### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fllprbt** [3daddict/memory-match-react#16]
I had the following error running `npm install`:
`✖ Error: pngquant failed to build, make sure that libpng-dev is installed.`

For my system (debian 9) it was fixed by running: 
`apt install libpng-dev`

This may also happen to Ubuntu and other linux distros. Please add it to the README.

**Comment by 3daddict** [comment]
Thanks for the bug fix @fllprbt!!!! I'll get this added.
