### ISSUE TITLE
Need Cards to have Icons using Font Awesome

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#2]
Make some cards to play the game to match font awesome icons. Lets start with 12 cards and 6 icons to match.

**Comment by arda971** [comment]
ok i will add icon

**Comment by arda971** [comment]
how do you push to origin master after changed

**Comment by 3daddict** [comment]
Try to create a new branch and then do a pull request comparing the new branch the dev branch.

**Comment by arda971** [comment]
i did a icon branch did not work i am not allowed to push

**Comment by arda971** [comment]
i try with dev

**Comment by 3daddict** [comment]
Great just submitting the pull request. I'm getting an error after npm installing react-fontawesome
`Could not find icon {prefix: "fas", iconName: "spa"}`
Do you know what is causing this?

**Comment by arda971** [comment]
you need to import the Fontawesome libraries in the app.js and then you can import the icon that you need
look at my second pull request in all in there

**Comment by arda971** [comment]
npm i --save @fortawesome/fontawesome-svg-core   npm i --save @fortawesome/free-solid-svg-icons   npm i --save @fortawesome/react-fontawesome

**Comment by 3daddict** [comment]
Yep that second pull request fixed the issue. Would you like to make the 12 cards with 6 icons to match?
Here is an example: https://scotch.io/tutorials/how-to-build-a-memory-matching-game-in-javascript
I have the flip function already programmed where the color sides will be the icon.
You can keep the current icons you made as the back of the cards,
Let me know if you have questions.

**Comment by arda971** [comment]
the cards are they random and unique ?  should i use the three color so 4 per color?

**Comment by 3daddict** [comment]
To start card location can be static. Later we can make a feature to populate the dom randomly on each game start. Colors can be removed, they were there to show front and back of the card.

**Comment by 3daddict** [comment]
@arda971 very nice work!!!
