### ISSUE TITLE
Create a Stats Area with Gameplay Info

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#23]
Before you begin:

**Confirm that you're working on this issue so I can add assigned label.**

Use `dev` branch as a base for your PR.

Read the contribution guide for info how to setup project, run tests and use development version of packages.

Create a Stats Area that will eventually go in the side nav once that issue completed and is merged.
**Stats Container**

- [ ] Games Played - Show how many times the game is played
- [ ] Add a Start new Game button and function to re-populate the DOM with cards
- [x] Number of Attempts - number of times the user has clicked on cards
- [ ] Accuracy (how many times they got it right / number of total clicks for the current game

**Comment by BennyCarlsson** [comment]
Would like to add Number of Attempts

**Comment by 3daddict** [comment]
> Would like to add Number of Attempts

You got it!

**Comment by 3daddict** [comment]
> Hey @3daddict . I'd like to take the other 3 tasks.

You got it!

**Comment by 3daddict** [comment]
> * Make attempts only count when there is a second click; (I'd recommend that)

@klauskpm great feedback, please go with your recommended approach.
