### ISSUE TITLE
Create linter command

### ISSUE THREAD

**Issue by mateoguzmana** [3daddict/memory-match-react#29]
The project is currently using `eslint@4.19.1`. It would be nice to implement a npm command to check the code format.

The command should be `npm run lint`, and this should check the code format with the eslint library.

**Comment by Daguilar94** [comment]
Hello, can I resolve this issue?

**Comment by mateoguzmana** [comment]
Sure! @Daguilar94.

@3daddict please assigned this task. Thanks!
