### ISSUE TITLE
Need html layout - Top Nav, Side Nav, Footer

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#3]
Create a layout using pure css no frameworks.

**Comment by sakethramanujam** [comment]
Hey! @3daddict let me do that!

**Comment by 3daddict** [comment]
@sakethramanujam are you still working on the layout?

**Comment by phavor** [comment]
Can I have this? @3daddict

**Comment by Gh05d** [comment]
I created a grid layout for the game. Did not work on footer, sidebar or top nav.

**Comment by 3daddict** [comment]
@phavor you can make the  footer, sidebar or top nav.

@Gh05d Nice! go ahead and make a pr for the grid.

**Comment by sakethramanujam** [comment]
> @sakethramanujam are you still working on the layout?

Yeah!
I was wondering in which folder do I place it.

**Comment by 3daddict** [comment]
> > @sakethramanujam are you still working on the layout?
> 
> Yeah!
> I was wondering in which folder do I place it.

You can place it in the components folder and import it to index.js so the app in nested inside the main area of your layout.

**Comment by 3daddict** [comment]
> I created a grid layout for the game. Did not work on footer, sidebar or top nav.

@Gh05d Excellent work on the grid with effects!!!

**Comment by Gh05d** [comment]
Thx. Happy that you like it.

**Comment by Gh05d** [comment]
Is there anything else to work on?

**Comment by sakethramanujam** [comment]
@3daddict Yes I got it working. The only problem I've been facing is with the network. It's only up today.
