### ISSUE TITLE
Refactor Card Component

### ISSUE THREAD

**Issue by mateoguzmana** [3daddict/memory-match-react#30]
Refactor Card component in order to have this component more readable and scalable.

The component is located at `memory-match-react/src/components/card.js`.

**Comment by robinHurtado** [comment]
I think i can work on it @mateoguzmana

**Comment by mateoguzmana** [comment]
Perfect!

@3daddict please check :)

**Comment by 3daddict** [comment]
@robinHurtado Nice work, Do we need the yarn.lock file in the PR or should that be .gitigonred?

**Comment by mateoguzmana** [comment]
@3daddict, @robinHurtado I think yarn.lock should be ignore as well.

**Comment by robinHurtado** [comment]
Hello @3daddict  it should be added in the .gitignore file, im gonna do it

**Comment by robinHurtado** [comment]
Ok Done the yarn.lock is in .gitignore file @3daddict
