### ISSUE TITLE
Make a responsive Flexbox Layout - SideNav with Header and Footer Sections

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#53]
Before you begin:
Confirm that you're working on this issue so I can add assigned label.
**Use `dev` branch as a base for your PR.**
Read the contribution guide for info how to setup project, run tests and use development version of packages.

**### Style enhancement - Responsive Layout**
- [ ] Create a Flexbox Layout with Side Nav, Header and Footer Section
    -> You can use this as an exmaple: [https://codepen.io/3daddict/pen/oaxbEw](https://codepen.io/3daddict/pen/oaxbEw)

- [ ] Place Game Stats in Header
- [ ] Place Buttons and create temp "#" nav links in Footer
        1. Game
        2. Contributers
        3. Randomize Button
        4. Start New Game Button

**Comment by sunilsj99** [comment]
@3daddict Can i work on this issue ??

**Comment by 3daddict** [comment]
@sunilsj99 You have been assigned this issue :-)

**Comment by sunilsj99** [comment]
Can you specify what functionality should be there in side nav ??

**Comment by sunilsj99** [comment]
@3daddict  Yes, this is a good idea !!

**Comment by sakethramanujam** [comment]
May be we can add a highscores button! Like a list of all previous scores. But it would need a DB! Any plans on this?

**Comment by 3daddict** [comment]
> May be we can add a highscores button! Like a list of all previous scores. But it would need a DB! Any plans on this?

@sakethramanujam not planning on adding a db to this project. Anyway to use local storage?

**Comment by 3daddict** [comment]
> > > May be we can add a highscores button! Like a list of all previous scores. But it would need a DB! Any plans on this?
> > 
> > 
> > @sakethramanujam not planning on adding a db to this project. Anyway to use local storage?
> 
> @3daddict Yes there is!
> 
> * We could have a hidden text file **Or**
> * The react app itself to store the highscore as a json on another route ie., the first score as a highscore and then on check for if the newer score is greater than previous one and then update the high score.
>   Doing the Second would be easier and also lasts only if the server session isn't terminated.

@sakethramanujam Lets go with the second option like you suggest. Go ahead and create the issue and I'll get it assigned to you.
