### ISSUE TITLE
Highscores Button/Feature 

### ISSUE THREAD

**Issue by sakethramanujam** [3daddict/memory-match-react#60]
**Is your feature request related to a problem? Please describe.**
The game is getting quite good with respect to UI/UX, and also the score. I feel that we add more intuition into it by giving a thought about adding HighScores 🌠 .

**Describe the solution you'd like**
There are two possible methods, but I prefer suggesting only one, let's say we are currently on a session 💻  ie., the server is started and we're playing a game. After the first gameplay, we can store the score and call it high score. For subsequent games that are played on this session, we check with the previous score and update if higher.

**Describe alternatives you've considered**
Using offline 📝 text file preferably a hidden one to save all scores and checking them. 

So, let's see if we can get this done.

**Comment by JonatanSCS** [comment]
Take this <3

**Comment by sakethramanujam** [comment]
Sorry for the delay! 🎓 some assignments delayed this dev
