### ISSUE TITLE
Number of attempts is shown twice

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#63]
**Describe the bug**
Number of attempts is shown twice.

**Expected behavior**
Please remove the <h1 id="numberOfAttempts">0 - Attempts</h1> that is outside of the gameStats container.

**Additional context**
Great for first timers please create a PR to `dev` branch please ask for the task so it can be assigned to you

**Comment by Alexius08** [comment]
I'll tackle this one.

**Comment by 3daddict** [comment]
> I'll tackle this one.

You got it!
