### ISSUE TITLE
Modify the Layout and Cards to be fully responsive to screen sizes

### ISSUE THREAD

**Issue by 3daddict** [3daddict/memory-match-react#64]
*Make the game page fully responsive. Currently the cards are a fixed size with non-consistent margins.*

**Modify the game page to be responsive to all screen sizes.**

- [x] Cards should shrink and grow based on screen size. Margins should be equal T,R, B, L.
- [x] Bottom buttons should not be covered by cards.
- [x] Left and Right Side Navs should collapse on smaller screen widths.

Let's try to achieve this using pure css with Flexbox.

**Additional context**
Please ask for the task to be assigned the issue. Make all PR's to `dev` branch.

**Comment by pandaa880** [comment]
I would like to work on this one.

**Comment by aparrett** [comment]
I was just typing that xD

**Comment by 3daddict** [comment]
> I would like to work on this one.

@pandaa880 for the win! You got it!

**Comment by 3daddict** [comment]
> Should I directly change the CSS in assets folder ?

Yes you can update the file directly

**Comment by 3daddict** [comment]
> are we targeting mobile device ?
> Because there are so many cards and setting them up in mobile won't be good UX. So should i just adjust layout for screens bigger than mobile ?

Maybe just target desktop and tablet screen sizes.
It would be good to have it do something on mobile even if the cards are very small.

**Comment by pandaa880** [comment]
I have opened PR. Please review it and let me know for other changes.

**Comment by 3daddict** [comment]
Nice work @pandaa880 !!!!
