### ISSUE TITLE
flipping third card issue

### ISSUE THREAD

**Issue by kzack123** [3daddict/memory-match-react#71]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
`newRevealStates.forEach(function(el) {
      if (el === true) {
        cardsFlipped++;
      } else {
        return;
      }
    });`

**Comment by 3daddict** [comment]
@kzack123 Nice work on the issue and pull request!
